### ISSUE TITLE
 Error: Cannot match any routes

### ISSUE THREAD

**Issue by ghost** [revoxltd/pages-admin-docs#2]
Hello,
I have an issue when i run the app (ng serve):
![image](https://user-images.githubusercontent.com/3184758/73281271-4c05ef00-4222-11ea-8959-3333beb4f82d.png)

Please advise.

TIA.

**Comment by MalithHatananchchige** [comment]
Hi there

This is a wrong place to ask questions but you should be on the following URLs first

http://localhost:4200/condensed/
http://localhost:4200/corporate/
http://localhost:4200/simplywhite/
http://localhost:4200/executive/
http://localhost:4200/casual/
